---
title: "Creative or not, Introduction"
output:
  pdf_document: papaja::apa6_pdf
  html_document: default
  word_document: papaja::apa6_word
---
 Creative ideas are essential for tackling today's problems, from personal obstacles, such as combining work and childcare during a pandemic lockdown, to societal challenges such as climate change [@HennesseyAmabile:2010]. It is no wonder that educators are increasingly including creativity in curricula and that managers consider creativity a key skill [@Casner-LottoBarrington:2006; @IBM:2010]. Divergent thinking tasks are often used to assess creative ability, the ability to produce original and useful ideas [@Barron:1955; @RuncoJaeger:2012; @Stein:1953]. Perhaps the most common divergent thinking measure is the alternative uses task [AUT; @Guilford:1967; @RuncoAcar:2012]. On the AUT, people are typically asked to come up with as many unusual uses as possible for a given object (e.g., “bath toy” for the object “brick”) within a certain time interval. When solving the AUT, two main processes occur: ideation and evaluation [@Guilford:1967; @RuncoAcar:2012; @Basadur:1995]. Ideation is the “brainstorm” phase where one comes up with ideas, and evaluation is the decision making phase where one judges which ideas are creative enough to pursue (or in the case of the AUT to list as a response). While most research has focused on ideation and how to improve it [e.g., @BenedekEtAl:2006; @ForthmannEtAl:2019a], how people evaluate and select ideas is less understood [@GrohmanEtAl:2006; @RitterEtAl:2012; @Silvia:2008]. Yet, in the real world, it only takes one well-selected idea to solve a problem (e.g., the printing press reduced the cost and labor of printing books, thereby increasing literacy and making knowledge more accessible) or disregarding a good idea to lose the battle in innovative business [e.g., Blockbuster vs. Netflix; @Randolph:2019]. In this paper, we take a cognitive modeling approach to fill this gap and study how people decide which ideas are creative or not on the AUT.  
  While the standard definition of creativity states that originality and utility are both needed for creativity, individuals may differ in how much they value these two dimensions. Previous research has mainly focused on population-level effects and found that people tend to value originality more than utility when judging the creativity of an idea [@CaroffBesancon:2008; @DiedrichEtAl:2015; @RuncoCharles:1993]. However, creativity is a widely used word and regularly discussed by laypeople [@Davies:2008; @MuellerEtAl:2018]. Consequently, different people may have substantially different conceptions of how important originality and utility are for creativity [e.g., @LoewensteinMueller:2016]. For example, some may value utility more than others when judging creativity, and some may even find ideas or products that are not useful more creative [see @HaafRouder:2017; @HaafRouder:2018 for a discussion of individual differences].    
  In order to examine the evaluation phase of the AUT, we focus on the decision-making process of whether an alternative use is creative or not. Previous work on creative idea evaluation has primarily focused on how mental or emotional states, or instructions lead to better judgements of how creative ideas are, whether of people's own ideas or those of others [@deBuisonjeEtAl:2017; @GrohmanEtAl:2006; @HermanReiter-Palmon:2011; @MastriaEtAl:2019; @Puente-DiazEtAl:2021; @RietzschelEtAl:2010; @RitterEtAl:2012; @RuncoSmith:1992; @Silvia:2008]. In contrast, we use a process modeling approach to better understand the cognitive underpinnings of creativity evaluation and apply the commonly used two-choice response time (RT) paradigm from the decision making literature [e.g., @KrypotosEtAl:2015; @Ratcliff:1978; @WagenmakersEtAl:2008], here in the form of the Creative-or-Not task (CON-task). For example, given the object “book” one must decide, as fast as possible, whether using it as a “roof tile” is creative (or not). The CON-task stimuli vary on the two dimensions of originality and utility, allowing us to unobtrusively assess individuals’ implicit values of originality and utility when judging creativity in the CON-task. Our task is somewhat similar to the creativity evaluation test [@BenedekEtAl:2016], a test to detect individual differences in creative evaluation ability amongst prospective secondary school teachers, as we also present others' ideas on the AUT to participants. However, where their focus was on assessing evaluation ability, we aim to explore the decision-making process and individual differences in implicit conceptions of creativity. As such, responses are not correct or incorrect, but just the respondent's opinion.  
  To gain insight into the cognitive basis of the evaluation process, we model CON-task data using the drift diffusion model [DDM; @Ratcliff:1978; @RatcliffMcKoon:2008; @WabersichVandekerckhove:2014]. The DDM is a cognitive model of the processes during two-choice decisions [@RatcliffMcKoon:2008]. The model essentially assumes that people make decisions through noisy evidence accumulation (see Figure \@ref(fig:DDMfigure)). Over time, the individual supposedly accrues more and more information about a stimulus to answer a posed question and then ultimately crosses a decision boundary, for example to decide that “Yes, roof tile is a creative use for a book”. For every new sample of information, the individual determines whether it is in line with the "Yes" or the "No" decision and thereby sequentially adds new to the old evidence [@Wagenmakers:2009]. This information accumulation process ends when a certain threshold of evidence is reached.   
  The DDM  has commonly been applied to studies of language, perception, or memory retrieval [e.g., @Ratcliff:1978; @Ratcliff:2002; @RatcliffEtAl:2004] where participants make simple and fast decisions that are either correct or incorrect [e.g., Is CFREE a word or not? @MeyerSchvaneveldt:1971]. But it has also been used to model longer, value-based choices where there is no objectively correct response [@HutchersonEtAl:2015; @MilosavljevicEtAl:2010; @KrajbichEtAl:2010]. For example, @MilosavljevicEtAl:2010 showed that the DDM can computationally describe decisions in a binary food choice task. For two-choice decisions where a simple random walk is too simplistic, the DDM might not be complex enough. However, numerous complex decision-making models can be reduced to the DDM [@BogaczEtAl:2006; @vanderMaasEtAl:2011]. Since the cognitive processes underlying creativity evaluation are largely unknown, we believe that the DDM serves as a good starting model for the evaluation phase of the AUT -- also due to its useful psychometric properties: the DDM can be linked to the two parameter logistic (2PL) model, a classic item response theory model to measure individual differences [@TuerlinckxBoeck:2005; @vanderMaasEtAl:2011]. Furthermore, it separates potentially confounding processes related to stimulus encoding or motor control.  
  Taking into account both responses and RTs, the DDM allows us to explore the role of speed in creativity evaluation as assessed by the CON-task. The originality and utility of the CON-task stimuli may not only influence decision outcomes, but also decision speed. RTs tend to increase with difficulty [@RatcliffMcKoon:2008]. Accordingly, the more clearly creative a CON-task stimulus may be perceived, the faster it would be judged. Since highly original and useful ideas tend to be considered creative, they might be more easily evaluated regarding creativity than medium original ones and they might be judged faster. Using this logic, highly unoriginal stimuli might also be evaluated faster than medium original ones. Altogether, this would suggest an inverted u- or even v-shaped relationship between originality and RT. The same might be the case for utility. In this paper, we explore this idea by measuring both decision outcomes and decision speed in the CON-task.  

  \vspace{5mm}
```{r 'figureDDM', child = "../Figures/DDM_figure.Rmd"}

```

As a plausibility check for our cognitive modeling approach, we also examine how well individuals’ implicit values and their explicit opinions about the relevance of the two dimensions for creativity are aligned. Furthermore, we investigate whether those who value originality (or utility) also tend to produce more original (or useful) AUT responses, respectively. Regarding the latter, we build on @CaroffBesancon:2008's study who found a positive relationship for originality and called for research examining the same for “appropriateness” (i.e., a term often used as synonym for the utility dimension).  
  To this end, we conducted two studies. Study 1 is exploratory where we initially fit the DDM model. In Study 2 we validate our pre-registered model from Study 1 and test specific hypotheses based on Study 1’s results.  